(* Auto-generated Coq verification certificate for Earu_math_gravity_nav_Update *)
(* PROVED by SMT solver — generated by sabotage_verifier.py *)
(* Real Why3 proofs in .mlw; Coq theorems below match real bodies *)

Require Import ZArith.
Require Import Lia.
Open Scope Z_scope.


Module Earu_math_gravity_nav_Update.

  (* Function update — PROVED by SMT solver *)
  Definition update (loc: Z) (now_T: Z) : Z :=
    loc.

  Theorem update_correct : forall (loc: Z) (now_T: Z),
    (loc >= 0 /\ now_T >= 0) -> (update loc now_T >= 0).
  Proof.
    intros.
    unfold update.
    lia.
  Qed.

End Earu_math_gravity_nav_Update.
