(* Auto-generated Coq verification certificate for Earu_io_YN *)
(* UNPROVED — obligation stub — generated by sabotage_verifier.py *)
(* Real Why3 proofs in .mlw; Coq theorems below match real bodies *)

Require Import ZArith.
Require Import Lia.
Require Import Bool.
Open Scope Z_scope.


Module Earu_io_YN.

  (* Function yN — UNPROVED — obligation stub *)
  Definition yN (val: bool) : Z :=
    (if val then """Yes""" else """No""").

  Theorem yN_correct : forall (val: bool),
    (true, Post => true) -> (True).
  Proof.
    intros.
    admit. (* obligation not discharged by SMT solver *)
  Admitted.

End Earu_io_YN.
