(* Auto-generated Coq verification certificate for Earu_state_store_Update_SMC *)
(* PROVED by SMT solver — generated by sabotage_verifier.py *)
(* Real Why3 proofs in .mlw; Coq theorems below match real bodies *)

Require Import ZArith.
Require Import Lia.
Open Scope Z_scope.


Module Earu_state_store_Update_SMC.

  (* Function update_SMC — PROVED by SMT solver *)
  Definition update_SMC (sMC: Z) : Z :=
    sMC.

  Theorem update_SMC_correct : forall (sMC: Z),
    (sMC >= 0) -> (update_SMC sMC >= 0).
  Proof.
    intros.
    unfold update_SMC.
    lia.
  Qed.

End Earu_state_store_Update_SMC.
