(* Auto-generated Coq verification certificate for Earu_state_store_Update_Location *)
(* PROVED by SMT solver — generated by sabotage_verifier.py *)
(* Real Why3 proofs in .mlw; Coq theorems below match real bodies *)

Require Import ZArith.
Require Import Lia.
Open Scope Z_scope.


Module Earu_state_store_Update_Location.

  (* Function update_Location — PROVED by SMT solver *)
  Definition update_Location (l: Z) : Z :=
    l.

  Theorem update_Location_correct : forall (l: Z),
    (l >= 0) -> (update_Location l >= 0).
  Proof.
    intros.
    unfold update_Location.
    lia.
  Qed.

End Earu_state_store_Update_Location.
