(* Auto-generated Coq verification certificate for Earu_state_store_Get_Sig_Loc_Count *)
(* UNPROVED — obligation stub — generated by sabotage_verifier.py *)
(* Real Why3 proofs in .mlw; Coq theorems below match real bodies *)

Require Import ZArith.
Require Import Lia.
Open Scope Z_scope.


Module Earu_state_store_Get_Sig_Loc_Count.

  (* Function get_Sig_Loc_Count — UNPROVED — obligation stub *)
  Definition get_Sig_Loc_Count (count: Z) : Z :=
    count.

  Theorem get_Sig_Loc_Count_correct : forall (count: Z),
    (true, Post => true) -> (True).
  Proof.
    intros.
    admit. (* obligation not discharged by SMT solver *)
  Admitted.

End Earu_state_store_Get_Sig_Loc_Count.
