(* Auto-generated Coq verification certificate for Earu_sig_loc_store_Sig_Loc_Json_Path *)
(* UNPROVED — obligation stub — generated by sabotage_verifier.py *)
(* Real Why3 proofs in .mlw; Coq theorems below match real bodies *)

Require Import ZArith.
Require Import Lia.
Open Scope Z_scope.


Module Earu_sig_loc_store_Sig_Loc_Json_Path.

  (* Function sig_Loc_Json_Path — UNPROVED — obligation stub *)
  Definition sig_Loc_Json_Path (n: Z) : Z :=
    Earu.IO.Project_Root & "/save_state/significant_locations.json".

  Theorem sig_Loc_Json_Path_correct : forall (n: Z),
    (True) -> (sig_Loc_Json_Path n >= 0).
  Proof.
    intros.
    admit. (* obligation not discharged by SMT solver *)
  Admitted.

End Earu_sig_loc_store_Sig_Loc_Json_Path.
