(* Auto-generated Coq verification certificate for Earu_io_Project_Root *)
(* UNPROVED — obligation stub — generated by sabotage_verifier.py *)
(* Real Why3 proofs in .mlw; Coq theorems below match real bodies *)

Require Import ZArith.
Require Import Lia.
Open Scope Z_scope.


Module Earu_io_Project_Root.

  (* Function project_Root — UNPROVED — obligation stub *)
  Definition project_Root (n: Z) : Z :=
    Ada.Environment_Variables.Value ("EARU_HOME").

  Theorem project_Root_correct : forall (n: Z),
    (True) -> (project_Root n >= 0).
  Proof.
    intros.
    admit. (* obligation not discharged by SMT solver *)
  Admitted.

End Earu_io_Project_Root.
