(* Auto-generated Coq verification certificate for Earu_ntrip_Send_String *)
(* UNPROVED — obligation stub — generated by sabotage_verifier.py *)
(* Real Why3 proofs in .mlw; Coq theorems below match real bodies *)

Require Import ZArith.
Require Import Lia.
Require Import String.
Open Scope string_scope.
Open Scope Z_scope.


Module Earu_ntrip_Send_String.

  (* Function send_String — UNPROVED — obligation stub *)
  Definition send_String (s: Z) (str: string) : Z :=
    s.

  Theorem send_String_correct : forall (s: Z) (str: string),
    (true, Post => true) -> (True).
  Proof.
    intros.
    admit. (* obligation not discharged by SMT solver *)
  Admitted.

End Earu_ntrip_Send_String.
