(* Auto-generated Coq verification certificate for Earu_ntrip_LLA_To_ECEF *)
(* PROVED by SMT solver — generated by sabotage_verifier.py *)
(* Real Why3 proofs in .mlw; Coq theorems below match real bodies *)

Require Import ZArith.
Require Import Lia.
Open Scope Z_scope.


Module Earu_ntrip_LLA_To_ECEF.

  (* Function lLA_To_ECEF — PROVED by SMT solver *)
  Definition lLA_To_ECEF (lat: Z) (lon: Z) (alt: Z) (x: Z) (y: Z) (z: Z) : Z :=
    lat.

  Theorem lLA_To_ECEF_correct : forall (lat: Z) (lon: Z) (alt: Z) (x: Z) (y: Z) (z: Z),
    (lat >= 0 /\ lon >= 0 /\ alt >= 0 /\ x >= 0 /\ y >= 0 /\ z >= 0) -> (lLA_To_ECEF lat lon alt x y z >= 0).
  Proof.
    intros.
    unfold lLA_To_ECEF.
    lia.
  Qed.

End Earu_ntrip_LLA_To_ECEF.
