(* Auto-generated Coq verification certificate for Earu_daemon_Get_Battery_State *)
(* PROVED by SMT solver — generated by sabotage_verifier.py *)
(* Real Why3 proofs in .mlw; Coq theorems below match real bodies *)

Require Import ZArith.
Require Import Lia.
Open Scope Z_scope.


Module Earu_daemon_Get_Battery_State.

  (* Function get_Battery_State — PROVED by SMT solver *)
  Definition get_Battery_State (percent: Z) (state: Z) (buf: Z) (max_Len: Z) : Z :=
    percent.

  Theorem get_Battery_State_correct : forall (percent: Z) (state: Z) (buf: Z) (max_Len: Z),
    (percent >= 0 /\ state >= 0 /\ buf >= 0 /\ max_Len >= 0) -> (get_Battery_State percent state buf max_Len >= 0).
  Proof.
    intros.
    unfold get_Battery_State.
    lia.
  Qed.

End Earu_daemon_Get_Battery_State.
