(* Auto-generated Coq verification certificate for Earu_bcg_detection_Bounded *)
(* PROVED by SMT solver — generated by sabotage_verifier.py *)
(* Real Why3 proofs in .mlw; Coq theorems below match real bodies *)

Require Import ZArith.
Require Import Lia.
Open Scope Z_scope.


Module Earu_bcg_detection_Bounded.

  (* Function bounded — PROVED by SMT solver *)
  Definition bounded (s: Z) : Z :=
    s.

  Theorem bounded_correct : forall (s: Z),
    (s >= 0) -> (bounded s >= 0).
  Proof.
    intros.
    unfold bounded.
    lia.
  Qed.

End Earu_bcg_detection_Bounded.
