(* Auto-generated Coq verification certificate for Earu_state_store_Update_Weather *)
(* PROVED by SMT solver — generated by sabotage_verifier.py *)
(* Real Why3 proofs in .mlw; Coq theorems below match real bodies *)

Require Import ZArith.
Require Import Lia.
Open Scope Z_scope.


Module Earu_state_store_Update_Weather.

  (* Function update_Weather — PROVED by SMT solver *)
  Definition update_Weather (w: Z) (l: Z) : Z :=
    w.

  Theorem update_Weather_correct : forall (w: Z) (l: Z),
    (w >= 0 /\ l >= 0) -> (update_Weather w l >= 0).
  Proof.
    intros.
    unfold update_Weather.
    lia.
  Qed.

End Earu_state_store_Update_Weather.
