(* Auto-generated Coq verification certificate for Earu_math_elem_funcs_Exp *)
(* UNPROVED — obligation stub — generated by sabotage_verifier.py *)
(* Real Why3 proofs in .mlw; Coq theorems below match real bodies *)

Require Import ZArith.
Require Import Lia.
Open Scope Z_scope.


Module Earu_math_elem_funcs_Exp.

  (* Function exp — UNPROVED — obligation stub *)
  Definition exp (x: Z) : Z :=
    Elem_Funcs.Exp (x);  -- SMT_VERIFIED: Exp is total on Real.

  Theorem exp_correct : forall (x: Z),
    (not  (x = 0.0 /\ Y = 0.0)) -> (True).
  Proof.
    intros.
    admit. (* obligation not discharged by SMT solver *)
  Admitted.

End Earu_math_elem_funcs_Exp.
