(* Auto-generated Coq verification certificate for Earu_io_Run_Dir *)
(* UNPROVED — obligation stub — generated by sabotage_verifier.py *)
(* Real Why3 proofs in .mlw; Coq theorems below match real bodies *)

Require Import ZArith.
Require Import Lia.
Open Scope Z_scope.


Module Earu_io_Run_Dir.

  (* Function run_Dir — UNPROVED — obligation stub *)
  Definition run_Dir (n: Z) : Z :=
    Project_Root & "/EARU_daemon/run".

  Theorem run_Dir_correct : forall (n: Z),
    (True) -> (run_Dir n >= 0).
  Proof.
    intros.
    admit. (* obligation not discharged by SMT solver *)
  Admitted.

End Earu_io_Run_Dir.
