(* Auto-generated Coq verification certificate for Earu_io_AL *)
(* UNPROVED — obligation stub — generated by sabotage_verifier.py *)
(* Real Why3 proofs in .mlw; Coq theorems below match real bodies *)

Require Import ZArith.
Require Import Lia.
Require Import Bool.
Require Import String.
Open Scope string_scope.
Open Scope Z_scope.


Module Earu_io_AL.

  (* Function aL — UNPROVED — obligation stub *)
  Definition aL (key: string) (val: Z) (comma: bool) : Z :=
    val.

  Theorem aL_correct : forall (key: string) (val: Z) (comma: bool),
    (val >= 0) -> (aL key val comma >= 0).
  Proof.
    intros.
    admit. (* obligation not discharged by SMT solver *)
  Admitted.

End Earu_io_AL.
