(* Auto-generated Coq verification certificate for Earu_io_C_Popen *)
(* UNPROVED — obligation stub — generated by sabotage_verifier.py *)
(* Real Why3 proofs in .mlw; Coq theorems below match real bodies *)

Require Import ZArith.
Require Import Lia.
Open Scope Z_scope.


Module Earu_io_C_Popen.

  (* Function c_Popen — UNPROVED — obligation stub *)
  Definition c_Popen (command: Z) (mode: Z) : Z :=
    command.

  Theorem c_Popen_correct : forall (command: Z) (mode: Z),
    (true, Post => true; -- c_binding) -> (true; -- c_binding).
  Proof.
    intros.
    admit. (* obligation not discharged by SMT solver *)
  Admitted.

End Earu_io_C_Popen.
