(* Auto-generated Coq verification certificate for Earu_state_store_Update_Parity *)
(* PROVED by SMT solver — generated by sabotage_verifier.py *)
(* Real Why3 proofs in .mlw; Coq theorems below match real bodies *)

Require Import ZArith.
Require Import Lia.
Open Scope Z_scope.


Module Earu_state_store_Update_Parity.

  (* Function update_Parity — PROVED by SMT solver *)
  Definition update_Parity (aug: Z) (ext: Z) (int_Val: Z) : Z :=
    aug.

  Theorem update_Parity_correct : forall (aug: Z) (ext: Z) (int_Val: Z),
    (aug >= 0 /\ ext >= 0 /\ int_Val >= 0) -> (update_Parity aug ext int_Val >= 0).
  Proof.
    intros.
    unfold update_Parity.
    lia.
  Qed.

End Earu_state_store_Update_Parity.
