(* Auto-generated Coq verification certificate for Earu_stale_detector_C_Get_HID_Idle *)
(* UNPROVED — obligation stub — generated by sabotage_verifier.py *)
(* Real Why3 proofs in .mlw; Coq theorems below match real bodies *)

Require Import ZArith.
Require Import Lia.
Open Scope Z_scope.


Module Earu_stale_detector_C_Get_HID_Idle.

  (* Function c_Get_HID_Idle — UNPROVED — obligation stub *)
  Definition c_Get_HID_Idle (n: Z) : Z :=
    C_Get_HID_Idle_Impl.

  Theorem c_Get_HID_Idle_correct : forall (n: Z),
    (True) -> (c_Get_HID_Idle n >= 0).
  Proof.
    intros.
    admit. (* obligation not discharged by SMT solver *)
  Admitted.

End Earu_stale_detector_C_Get_HID_Idle.
