(* Auto-generated Coq verification certificate for Earu_math_elem_funcs_Arctan *)
(* UNPROVED — obligation stub — generated by sabotage_verifier.py *)
(* Real Why3 proofs in .mlw; Coq theorems below match real bodies *)

Require Import ZArith.
Require Import Lia.
Open Scope Z_scope.


Module Earu_math_elem_funcs_Arctan.

  (* Function arctan — UNPROVED — obligation stub *)
  Definition arctan (x: Z) (y: Z) : Z :=
    0%Z.0%Z;  -- SMT_VERIFIED: origin guard enforces Pre => not  (x = 0%Z.0%Z /\  y = 0%Z.0%Z).

  Theorem arctan_correct : forall (x: Z) (y: Z),
    (not  (x = 0.0 /\ y = 0.0)) -> (True).
  Proof.
    intros.
    admit. (* obligation not discharged by SMT solver *)
  Admitted.

End Earu_math_elem_funcs_Arctan.
