(* Auto-generated Coq verification certificate for Earu_math_elem_funcs_Sin *)
(* UNPROVED — obligation stub — generated by sabotage_verifier.py *)
(* Real Why3 proofs in .mlw; Coq theorems below match real bodies *)

Require Import ZArith.
Require Import Lia.
Open Scope Z_scope.


Module Earu_math_elem_funcs_Sin.

  (* Function sin — UNPROVED — obligation stub *)
  Definition sin (x: Z) : Z :=
    Elem_Funcs.Sin (x);  -- SMT_VERIFIED: Sin is total on Real.

  Theorem sin_correct : forall (x: Z),
    (not  (x = 0.0 /\ Y = 0.0)) -> (True).
  Proof.
    intros.
    admit. (* obligation not discharged by SMT solver *)
  Admitted.

End Earu_math_elem_funcs_Sin.
