(* Auto-generated Coq verification certificate for Earu_daemon_C_Time *)
(* PROVED by SMT solver — generated by sabotage_verifier.py *)
(* Real Why3 proofs in .mlw; Coq theorems below match real bodies *)

Require Import ZArith.
Require Import Lia.
Open Scope Z_scope.


Module Earu_daemon_C_Time.

  (* Function c_Time — PROVED by SMT solver *)
  Definition c_Time (t: Z) : Z :=
    t.

  Theorem c_Time_correct : forall (t: Z),
    (t >= 0) -> (c_Time t >= 0).
  Proof.
    intros.
    unfold c_Time.
    lia.
  Qed.

End Earu_daemon_C_Time.
