(* Auto-generated Coq verification certificate for Earu_io_B *)
(* UNPROVED — obligation stub — generated by sabotage_verifier.py *)
(* Real Why3 proofs in .mlw; Coq theorems below match real bodies *)

Require Import ZArith.
Require Import Lia.
Require Import Bool.
Open Scope Z_scope.


Module Earu_io_B.

  (* Function b — UNPROVED — obligation stub *)
  Definition b (val: bool) : Z :=
    (if val then "true" else "false").

  Theorem b_correct : forall (val: bool),
    (True) -> (b val >= 0).
  Proof.
    intros.
    admit. (* obligation not discharged by SMT solver *)
  Admitted.

End Earu_io_B.
