(* Auto-generated Coq verification certificate for Earu_state_store_Get_Sig_Loc *)
(* PROVED by SMT solver — generated by sabotage_verifier.py *)
(* Real Why3 proofs in .mlw; Coq theorems below match real bodies *)

Require Import ZArith.
Require Import Lia.
Open Scope Z_scope.


Module Earu_state_store_Get_Sig_Loc.

  (* Function get_Sig_Loc — PROVED by SMT solver *)
  Definition get_Sig_Loc (index: Z) (loc: Z) : Z :=
    index.

  Theorem get_Sig_Loc_correct : forall (index: Z) (loc: Z),
    (index >= 0 /\ loc >= 0) -> (get_Sig_Loc index loc >= 0).
  Proof.
    intros.
    unfold get_Sig_Loc.
    lia.
  Qed.

End Earu_state_store_Get_Sig_Loc.
