(* Auto-generated Coq verification certificate for Earu_math_Trend_Dir *)
(* PROVED by SMT solver — generated by sabotage_verifier.py *)
(* Real Why3 proofs in .mlw; Coq theorems below match real bodies *)

Require Import ZArith.
Require Import Lia.
Open Scope Z_scope.


Module Earu_math_Trend_Dir.

  (* Function trend_Dir — PROVED by SMT solver *)
  Definition trend_Dir (v: Z) : Z :=
    v.

  Theorem trend_Dir_correct : forall (v: Z),
    (v >= 0) -> (trend_Dir v >= 0).
  Proof.
    intros.
    unfold trend_Dir.
    lia.
  Qed.

End Earu_math_Trend_Dir.
