(* Auto-generated Coq verification certificate for Earu_ntrip_Make_RTCM_1005 *)
(* UNPROVED — obligation stub — generated by sabotage_verifier.py *)
(* Real Why3 proofs in .mlw; Coq theorems below match real bodies *)

Require Import ZArith.
Require Import Lia.
Open Scope Z_scope.


Module Earu_ntrip_Make_RTCM_1005.

  (* Function make_RTCM_1005 — UNPROVED — obligation stub *)
  Definition make_RTCM_1005 (lat: Z) (lon: Z) (alt: Z) : Z :=
    lat.

  Theorem make_RTCM_1005_correct : forall (lat: Z) (lon: Z) (alt: Z),
    (true, Post => true) -> (True).
  Proof.
    intros.
    admit. (* obligation not discharged by SMT solver *)
  Admitted.

End Earu_ntrip_Make_RTCM_1005.
