(* Auto-generated Coq verification certificate for Earu_system_bridge_Read_SMC_Fans *)
(* PROVED by SMT solver — generated by sabotage_verifier.py *)
(* Real Why3 proofs in .mlw; Coq theorems below match real bodies *)

Require Import ZArith.
Require Import Lia.
Open Scope Z_scope.


Module Earu_system_bridge_Read_SMC_Fans.

  (* Function read_SMC_Fans — PROVED by SMT solver *)
  Definition read_SMC_Fans (sMC: Z) : Z :=
    sMC.

  Theorem read_SMC_Fans_correct : forall (sMC: Z),
    (sMC >= 0) -> (read_SMC_Fans sMC >= 0).
  Proof.
    intros.
    unfold read_SMC_Fans.
    lia.
  Qed.

End Earu_system_bridge_Read_SMC_Fans.
