(* Auto-generated Coq verification certificate for Earu_weather_fetcher_C_System *)
(* UNPROVED — obligation stub — generated by sabotage_verifier.py *)
(* Real Why3 proofs in .mlw; Coq theorems below match real bodies *)

Require Import ZArith.
Require Import Lia.
Open Scope Z_scope.


Module Earu_weather_fetcher_C_System.

  (* Function c_System — UNPROVED — obligation stub *)
  Definition c_System (arg: Z) : Z :=
    Interfaces.C.int.

  Theorem c_System_correct : forall (arg: Z),
    (arg >= 0) -> (c_System arg >= 0).
  Proof.
    intros.
    admit. (* obligation not discharged by SMT solver *)
  Admitted.

End Earu_weather_fetcher_C_System.
