(* Auto-generated Coq verification certificate for Earu_ntrip_Make_RTCM_1005 *)
(* PROVED by SMT solver — generated by sabotage_verifier.py *)
(* Real Why3 proofs in .mlw; Coq theorems below match real bodies *)

Require Import ZArith.
Require Import Lia.
Open Scope Z_scope.


Module Earu_ntrip_Make_RTCM_1005.

  (* Function make_RTCM_1005 — PROVED by SMT solver *)
  Definition make_RTCM_1005 (lat: Z) (lon: Z) (alt: Z) : Z :=
    lat.

  Theorem make_RTCM_1005_correct : forall (lat: Z) (lon: Z) (alt: Z),
    (lat >= 0 /\ lon >= 0 /\ alt >= 0) -> (make_RTCM_1005 lat lon alt >= 0).
  Proof.
    intros.
    unfold make_RTCM_1005.
    lia.
  Qed.

End Earu_ntrip_Make_RTCM_1005.
