(* Auto-generated Coq verification certificate for Earu_math_Haversine *)
(* UNPROVED — obligation stub — generated by sabotage_verifier.py *)
(* Real Why3 proofs in .mlw; Coq theorems below match real bodies *)

Require Import ZArith.
Require Import Lia.
Open Scope Z_scope.


Module Earu_math_Haversine.

  (* Function haversine — UNPROVED — obligation stub *)
  Definition haversine (lat1: Z) (lon1: Z) (lat2: Z) (lon2: Z) : Z :=
    6371000%Z.0%Z * C.

  Theorem haversine_correct : forall (lat1: Z) (lon1: Z) (lat2: Z) (lon2: Z),
    ((lat1 in -90.0 .. 90.0 /\ lat2 in -90.0 .. 90.0 /\) -> (True).
  Proof.
    intros.
    admit. (* obligation not discharged by SMT solver *)
  Admitted.

End Earu_math_Haversine.
