(* Auto-generated Coq verification certificate for Earu_ntrip_LLA_To_ECEF *)
(* UNPROVED — obligation stub — generated by sabotage_verifier.py *)
(* Real Why3 proofs in .mlw; Coq theorems below match real bodies *)

Require Import ZArith.
Require Import Lia.
Open Scope Z_scope.


Module Earu_ntrip_LLA_To_ECEF.

  (* Function lLA_To_ECEF — UNPROVED — obligation stub *)
  Definition lLA_To_ECEF (lat: Z) (lon: Z) (alt: Z) (x: Z) (y: Z) (z: Z) : Z :=
    lat.

  Theorem lLA_To_ECEF_correct : forall (lat: Z) (lon: Z) (alt: Z) (x: Z) (y: Z) (z: Z),
    (true, Post => true) -> (True).
  Proof.
    intros.
    admit. (* obligation not discharged by SMT solver *)
  Admitted.

End Earu_ntrip_LLA_To_ECEF.
