(* Auto-generated Coq verification certificate for Earu_math_gravity_nav_Normal_Gravity *)
(* UNPROVED — obligation stub — generated by sabotage_verifier.py *)
(* Real Why3 proofs in .mlw; Coq theorems below match real bodies *)

Require Import ZArith.
Require Import Lia.
Open Scope Z_scope.


Module Earu_math_gravity_nav_Normal_Gravity.

  (* Function normal_Gravity — UNPROVED — obligation stub *)
  Definition normal_Gravity (phi: Z) (h: Z) : Z :=
    Gamma_Equator * (1%Z.0%Z + Gamma_K * Sin2).

  Theorem normal_Gravity_correct : forall (phi: Z) (h: Z),
    (phi >= 0 /\ h >= 0) -> (normal_Gravity phi h >= 0).
  Proof.
    intros.
    admit. (* obligation not discharged by SMT solver *)
  Admitted.

End Earu_math_gravity_nav_Normal_Gravity.
