(* Auto-generated Coq verification certificate for Earu_system_bridge_To_Real *)
(* UNPROVED — obligation stub — generated by sabotage_verifier.py *)
(* Real Why3 proofs in .mlw; Coq theorems below match real bodies *)

Require Import ZArith.
Require Import Lia.
Open Scope Z_scope.


Module Earu_system_bridge_To_Real.

  (* Function to_Real — UNPROVED — obligation stub *)
  Definition to_Real (v: Z) : Z :=
    Real (v).

  Theorem to_Real_correct : forall (v: Z),
    (v >= 0) -> (to_Real v >= 0).
  Proof.
    intros.
    admit. (* obligation not discharged by SMT solver *)
  Admitted.

End Earu_system_bridge_To_Real.
