(* Auto-generated Coq verification certificate for Earu_state_store_Get_Sig_Loc_Count *)
(* PROVED by SMT solver — generated by sabotage_verifier.py *)
(* Real Why3 proofs in .mlw; Coq theorems below match real bodies *)

Require Import ZArith.
Require Import Lia.
Open Scope Z_scope.


Module Earu_state_store_Get_Sig_Loc_Count.

  (* Function get_Sig_Loc_Count — PROVED by SMT solver *)
  Definition get_Sig_Loc_Count (count: Z) : Z :=
    count.

  Theorem get_Sig_Loc_Count_correct : forall (count: Z),
    (count >= 0) -> (get_Sig_Loc_Count count >= 0).
  Proof.
    intros.
    unfold get_Sig_Loc_Count.
    lia.
  Qed.

End Earu_state_store_Get_Sig_Loc_Count.
