(* Auto-generated Coq verification certificate for Earu_state_store_Update_Misc *)
(* PROVED by SMT solver — generated by sabotage_verifier.py *)
(* Real Why3 proofs in .mlw; Coq theorems below match real bodies *)

Require Import ZArith.
Require Import Lia.
Open Scope Z_scope.


Module Earu_state_store_Update_Misc.

  (* Function update_Misc — PROVED by SMT solver *)
  Definition update_Misc (lid_Angle: Z) (lid_Speed: Z) (aLS: Z) : Z :=
    lid_Angle.

  Theorem update_Misc_correct : forall (lid_Angle: Z) (lid_Speed: Z) (aLS: Z),
    (lid_Angle >= 0 /\ lid_Speed >= 0 /\ aLS >= 0) -> (update_Misc lid_Angle lid_Speed aLS >= 0).
  Proof.
    intros.
    unfold update_Misc.
    lia.
  Qed.

End Earu_state_store_Update_Misc.
