(* Auto-generated Coq verification certificate for Earu_ntrip_To_U64 *)
(* UNPROVED — obligation stub — generated by sabotage_verifier.py *)
(* Real Why3 proofs in .mlw; Coq theorems below match real bodies *)

Require Import ZArith.
Require Import Lia.
Open Scope Z_scope.


Module Earu_ntrip_To_U64.

  (* Function to_U64 — UNPROVED — obligation stub *)
  Definition to_U64 (v: Z) : Z :=
    Unsigned_64 (v).

  Theorem to_U64_correct : forall (v: Z),
    (v >= 0 /\ v >= 0 — Make_RTCM_1005 clamps IX/IY/IZ to 0 before every call.) -> (to_U64 v = Unsigned_64 (v) /\ exact modular image of v — range check, not  a bit pun.).
  Proof.
    intros.
    admit. (* obligation not discharged by SMT solver *)
  Admitted.

End Earu_ntrip_To_U64.
